[package]
name = "orga-whereabouts"
version = "0.1.0-dev"
authors = ["Jochen Kupperschmidt"]
edition = "2021"
description = "Log orga whereabouts via RFID tags and buttons"
readme = "README.md"
homepage = "https://homework.nwsnet.de/"
repository = "https://github.com/homeworkprod"
license = "MIT"
keywords = ["rfid"]

[dependencies]
anyhow = "1.0"
clap = { version = "3.1.18", default-features = false, features = ["derive", "std"] }
evdev = { version = "0.11.4" }
flume = "0.10"
nanorand = "0.7.0"
rodio = { version = "0.15", default-features = false, features = ["mp3", "vorbis"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.5.9"
