[package]
name = "verbleiber"
version = "0.4.0"
authors = ["Jochen Kupperschmidt"]
edition = "2021"
rust-version = "1.71.1"
description = "Log organizer whereabouts on events via RFID tags and buttons"
readme = "README.md"
repository = "https://github.com/lanresort/verbleiber"
license = "MIT"
keywords = ["presence", "rfid"]

[dependencies]
anyhow = "1.0"
clap = { version = "4.4.6", default-features = false, features = ["derive", "error-context", "help", "std", "usage"] }
evdev = { version = "0.12.1" }
flume = "0.11.0"
nanorand = "0.7.0"
rodio = { version = "0.17.1", default-features = false, features = ["vorbis"] }
serde = { version = "1.0", features = ["derive"] }
ureq = { version = "2.8.0", features = ["json"] }
toml = "0.7.3"
