[package]
name = "verbleiber"
version = "0.1.0-dev"
authors = ["Jochen Kupperschmidt"]
edition = "2021"
description = "Log orga whereabouts via RFID tags and buttons"
readme = "README.md"
homepage = "https://homework.nwsnet.de/"
repository = "https://github.com/homeworkprod"
license = "MIT"
keywords = ["rfid"]

[dependencies]
anyhow = "1.0"
clap = { version = "3.1.18", default-features = false, features = ["derive", "std"] }
evdev = { version = "0.12.1" }
flume = "0.10"
nanorand = "0.7.0"
rodio = { version = "0.17.1", default-features = false, features = ["vorbis"] }
serde = { version = "1.0", features = ["derive"] }
ureq = { version = "2.6.2", features = ["json"] }
toml = "0.7.3"
