api_token = "__redacted__"
api_url = "https://byceps.example/api/v1/whereabouts/set_status"
sounds_path = "sounds"

[tags_to_user_ids]
"0000000001" = "ff4d72e5-f0c5-4097-b09d-5e5b634eb353"  # yogi

[user_sounds]
"ff4d72e5-f0c5-4097-b09d-5e5b634eb353" = "hallo-yogi.ogg"

[whereabouts_keys_to_ids]
present = "2ace4e57-e083-490b-ad10-3d214666db57"
away = "568d4a1e-5af0-43cd-8249-832ffc387e4d"
asleep = "92f92f15-fbc1-4e77-bd75-65186f9e4a4d"

[whereabouts_sounds]
present = [
    "na-endlich.ogg",
    "willkommen-zurueck.ogg",
]
away = [
    "auf-wiedersehen.ogg",
    "bis-bald.ogg",
]
asleep = [
    "gute-nacht-schlaf-schoen.ogg",
]
