reader_input_device = "/dev/input/event23"
button_input_device = "/dev/input/event42"
sounds_path = "sounds"

[buttons_to_key_codes]
button1 = "trigger"
button2 = "thumb"
button3 = "thumb2"
button4 = "top"
button5 = "tl"
button6 = "tr"
button7 = "tl2"
button8 = "tr2"

[api]
base_url = "https://byceps.example/api/v1/whereabouts"
client_token = "YOUR-CLIENT-TOKEN-GOES-HERE"
tls_verify = true
timeout_in_seconds = 10

[party]
party_id = "YOUR-PARTY-ID-GOES-HERE"

[party.buttons_to_whereabouts]
button1 = "orga-area"
button2 = "on-the-move"
button3 = "sleeping"
button4 = "mystery-zone"

[party.whereabouts_sounds]
"orga-area" = [
    "na-endlich",
    "willkommen-zurueck",
]
"on-the-move" = [
    "auf-wiedersehen",
    "bis-bald",
]
"sleeping" = [
    "gute-nacht-schlaf-schoen",
]
"mystery-zone" = [
    "willkommen-in-der-mystery-zone",
]
