reader_input_device = "/dev/input/event23"
button_input_device = "/dev/input/event42"
sounds_path = "sounds"

[api]
base_url = "https://byceps.example/api/v1/whereabouts"
client_token = "YOUR-CLIENT-TOKEN-GOES-HERE"
tls_verify = true
timeout_in_seconds = 10

[party]
party_id = "YOUR-PARTY-ID-GOES-HERE"

[party.buttons_to_whereabouts]
button1 = "orga-area"
button2 = "on-the-move"
button3 = "sleeping"
button4 = "mystery-zone"

[party.whereabouts_sounds]
"orga-area" = [
    "na-endlich.ogg",
    "willkommen-zurueck.ogg",
]
"on-the-move" = [
    "auf-wiedersehen.ogg",
    "bis-bald.ogg",
]
"sleeping" = [
    "gute-nacht-schlaf-schoen.ogg",
]
"mystery-zone" = [
    "willkommen-in-der-mystery-zone.ogg",
]
