name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allow manual workflow triggering from the "Actions" tab.
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Install system dependencies
        run: sudo apt-get --update install --assume-yes --no-install-recommends libasound2-dev

      - name: Show rustc version
        run: rustc --version

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose
