name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allow manual workflow triggering from the "Actions" tab.
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install --assume-yes libasound2-dev
    - name: Build
      run: rustc --version && cargo build --verbose
    - name: Test
      run: cargo test --verbose
